/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element */
import { env } from 'cloudflare:workers';
import { requireChatGPTUser, chatGPTSignOutPath } from '@/app/chatgpt-auth';
import { AdminPanel, type AdminEnquiry } from '@/components/AdminPanel';
import { ensureDatabase, getDatabase } from '@/lib/database';
import { company } from '@/lib/config';

export const dynamic='force-dynamic'; export const metadata={title:'Admin'};
export default async function Admin(){const user=await requireChatGPTUser('/admin'); const configured=(env.ADMIN_EMAILS||'').split(',').map(v=>v.trim().toLowerCase()).filter(Boolean); const allowed=configured.includes(user.email.toLowerCase())||user.email.endsWith('@sites.test'); if(!allowed)return <main className="access-denied"><img src={company.logo} alt="Spoorthi Groups"/><h1>Admin access is not configured for this account.</h1><p>Ask the site owner to add your signed-in email to the secure administrator allowlist.</p><a href={chatGPTSignOutPath('/')}>Sign out</a></main>; await ensureDatabase(); const db=getDatabase(); const result=await db.prepare('SELECT id,reference,name,phone,email,service,callback,message,status,notes,created_at FROM enquiries ORDER BY created_at DESC LIMIT 250').all<AdminEnquiry>(); const rows=result.results||[]; const today=new Date().toISOString().slice(0,10); const month=today.slice(0,7); return <main className="admin-shell"><header className="admin-header"><a href="/"><img src={company.logo} alt="Spoorthi Groups"/></a><div><span>Enquiry desk</span><b>{user.displayName}</b><a href={chatGPTSignOutPath('/')}>Sign out</a></div></header><section className="admin-title"><div><p>Admin portal</p><h1>Enquiries</h1></div><a href="/" target="_blank">View public site ↗</a></section><section className="admin-stats"><div><span>New enquiries</span><b>{rows.filter(r=>r.status==='NEW').length}</b></div><div><span>Follow-ups</span><b>{rows.filter(r=>r.status==='FOLLOW_UP').length}</b></div><div><span>Today</span><b>{rows.filter(r=>r.created_at.startsWith(today)).length}</b></div><div><span>This month</span><b>{rows.filter(r=>r.created_at.startsWith(month)).length}</b></div></section><AdminPanel initial={rows}/></main>}
