import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { PublicShell } from '@/components/PublicShell';
import { EnquiryForm } from '@/components/EnquiryForm';
import { createWhatsAppLink, services, type ServiceSlug } from '@/lib/config';

export function generateStaticParams() { return services.map((service)=>({slug:service.slug})); }
export async function generateMetadata({ params }:{params:Promise<{slug:string}>}):Promise<Metadata>{ const {slug}=await params; const service=services.find((item)=>item.slug===slug); return service?{title:service.label,description:service.summary}:{title:'Service'}; }

const modules: Record<ServiceSlug,{kicker:string;question:string;answer:string;lenses:{title:string;copy:string}[];note:string}> = {
  chits:{kicker:'Purpose before contribution',question:'What is this monthly discipline meant to make possible?',answer:'A useful chit conversation starts with the goal, the timeline and the capacity to contribute—not with a headline amount.',lenses:[{title:'Goal',copy:'Name the education, celebration, business or savings objective.'},{title:'Rhythm',copy:'Consider a monthly commitment that remains realistic.'},{title:'Mechanics',copy:'Understand auctions, obligations, fees and documentation.'}],note:'Chits involve financial commitments and provider-specific rules. Review the registered provider’s documentation before joining.'},
  'health-insurance':{kicker:'Cover in real life',question:'Would the policy still feel clear during a difficult hospital moment?',answer:'Look beyond the premium. Family composition, waiting periods, exclusions, room limits, co-payments and hospital access can all shape how cover works.',lenses:[{title:'People',copy:'Map every family member who needs protection.'},{title:'Care',copy:'Check hospitals, waiting periods and treatment conditions.'},{title:'Terms',copy:'Read exclusions, limits, co-payments and renewal rules.'}],note:'Insurance is subject to underwriting, policy terms and exclusions. Read the insurer’s policy wording and benefit illustration carefully.'},
  'life-insurance':{kicker:'Responsibilities made visible',question:'What should remain protected if income suddenly changes?',answer:'Life protection begins by understanding who depends on you, what commitments must continue and how long that responsibility may last.',lenses:[{title:'Family',copy:'Identify the people and responsibilities that depend on income.'},{title:'Time',copy:'Consider how obligations change across the years.'},{title:'Disclosure',copy:'Provide accurate information and review policy terms.'}],note:'Life insurance availability and pricing depend on insurer underwriting. No page content is a promise of cover or claim outcome.'},
  loans:{kicker:'Readiness before application',question:'Is the requirement clear enough to choose the right financing route?',answer:'Purpose, amount, repayment capacity, documentation and lender criteria all matter. A clearer application begins before a form is submitted.',lenses:[{title:'Purpose',copy:'Define the need and the amount with precision.'},{title:'Capacity',copy:'Understand income, obligations and repayment comfort.'},{title:'Evidence',copy:'Prepare accurate identity, income and business documents.'}],note:'All loans are subject to lender eligibility, credit assessment, pricing and approval. Spoorthi Groups cannot guarantee sanction.'},
  'real-estate':{kicker:'Context before commitment',question:'Does the property work for the life or investment plan around it?',answer:'The address is only one part of the decision. Budget, purpose, location, legal diligence, financing and time horizon deserve equal attention.',lenses:[{title:'Purpose',copy:'Separate end-use priorities from investment expectations.'},{title:'Place',copy:'Consider access, neighbourhood, infrastructure and fit.'},{title:'Proof',copy:'Carry out independent legal, title and financial verification.'}],note:'Property information can change. Buyers must independently verify title, approvals, pricing, developer claims and legal documentation.'},
};

export default async function ServicePage({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params; const service=services.find((item)=>item.slug===slug); if(!service) notFound();
  const contentModule=modules[service.slug];
  const formValue={chits:'CHITS','health-insurance':'HEALTH_INSURANCE','life-insurance':'LIFE_INSURANCE',loans:'LOANS','real-estate':'REAL_ESTATE'}[service.slug];
  return <PublicShell><main id="main-content" className={`service-world theme-${service.theme}`}>
    <section className="service-cinema"><div className="service-cinema-copy"><p className="eyebrow light"><span/> {service.number} • {service.label}</p><h1>{service.title}</h1><p>{service.summary}</p><div className="hero-actions"><a className="button button-primary" href="#service-enquiry">Speak with Spoorthi Groups</a><a className="button glass-button" href={createWhatsAppLink(service.whatsapp)} target="_blank" rel="noreferrer">WhatsApp about {service.shortName}</a></div></div><div className="service-motion-poster" aria-hidden="true"><span>{service.symbol}</span><i/><i/><i/><div><small>{service.number}</small><b>{service.scene}</b></div></div></section>
    <nav className="service-path" aria-label="Service journey"><a href="/#services">All services</a><span>→</span><b>{service.label}</b><i>Scroll to explore</i></nav>
    <section className="service-question"><p className="eyebrow"><span/> {contentModule.kicker}</p><h2>{contentModule.question}</h2><p>{contentModule.answer}</p></section>
    <section className="service-lenses"><div><span>Three lenses</span><h2>See the decision<br/><em>more completely.</em></h2></div><div className="lens-grid">{contentModule.lenses.map((lens,index)=><article key={lens.title}><span>0{index+1}</span><h3>{lens.title}</h3><p>{lens.copy}</p></article>)}</div></section>
    <section className="service-process upgraded-process"><div className="section-kicker"><span>How it works</span><p>A clear, assisted<br/>journey</p></div><div><h2>Start with the requirement.<br/><em>Understand the next steps.</em></h2><ol>{service.process.map((step,index)=><li key={step}><span>0{index+1}</span><h3>{step}</h3></li>)}</ol><div className="disclosure"><b>Important</b><p>{contentModule.note} Spoorthi Groups provides advisory and facilitation support; relevant provider terms govern every offering.</p></div></div></section>
    <section className="service-audience"><p className="eyebrow"><span/> A conversation may help when</p><div className="audience-grid"><div><span>01</span><h3>You know the goal but not the route.</h3></div><div><span>02</span><h3>The terminology is making the choice harder.</h3></div><div><span>03</span><h3>You want to prepare before speaking with a provider.</h3></div></div></section>
    <section className="service-enquiry" id="service-enquiry"><div><p className="eyebrow light"><span/> Request guidance from Spoorthi Groups</p><h2>Have a question about <em>{service.shortName.toLowerCase()}?</em></h2><p>Share a few basic details. A conversation does not create an obligation or guarantee eligibility.</p></div><div className="form-card"><EnquiryForm defaultService={formValue}/></div></section>
  </main></PublicShell>;
}
